Ruff
xBromsson/marley pull request #2
Opened 2023-08-14 20:03 UTC by pythoninthegrass

Ran `ruff check . --fix` and got this output:
```bash
# check
λ ruff check .
main.py:174:39: F541 [*] f-string without any placeholders
main.py:185:39: F541 [*] f-string without any placeholders
main.py:196:39: F541 [*] f-string without any placeholders
main.py:207:39: F541 [*] f-string without any placeholders
main.py:220:39: F541 [*] f-string without any placeholders
main.py:237:39: F541 [*] f-string without any placeholders
main.py:255:39: F541 [*] f-string without any placeholders
main.py:271:39: F541 [*] f-string without any placeholders
main.py:282:39: F541 [*] f-string without any placeholders
main.py:293:39: F541 [*] f-string without any placeholders
main.py:304:39: F541 [*] f-string without any placeholders
main.py:315:39: F541 [*] f-string without any placeholders
main.py:326:39: F541 [*] f-string without any placeholders
main.py:337:39: F541 [*] f-string without any placeholders
main.py:350:39: F541 [*] f-string without any placeholders
main.py:489:42: E712 [*] Comparison to `True` should be `cond is True` or `if cond:`
main.py:820:46: E712 [*] Comparison to `False` should be `cond is False` or `if not cond:`
main.py:830:19: E712 [*] Comparison to `True` should be `cond is True` or `if cond:`
main.py:848:30: E712 [*] Comparison to `False` should be `cond is False` or `if not cond:`
main.py:850:35: E712 [*] Comparison to `False` should be `cond is False` or `if not cond:`
main.py:867:44: E712 [*] Comparison to `False` should be `cond is False` or `if not cond:`
Found 21 errors.
[*] 21 potentially fixable with the --fix option.

# fix
λ ruff check . --fix
Found 21 errors (21 fixed, 0 remaining).
```

2023-08-14 20:08 UTC, pythoninthegrass commented
Probably shoulda removed the other 11 files but `¯\_(ツ)_/¯`

2023-08-17 16:42 UTC, xBromsson requested changes
I learned so much just reviewing/digesting all these changes and trying to understand the tools you used / changes you made and why. Very eye opening. Thank you for contributing. This is a great learning experience for me for sure.

2023-08-17 16:42 UTC, xBromsson commented on .github/FUNDING.yml
> +ko_fi: moraroy
Replace with a single Ko Fi username

2023-08-17 16:42 UTC, xBromsson commented on .github/FUNDING.yml
> +liberapay: moraroy
Replace with a single Liberpay username

2023-08-17 16:42 UTC, xBromsson commented on .gitignore
Am I right in understanding that many of these .gitignore files don't apply for this project currently but you are including them as more of a template for future needs (just in case)?

2023-08-17 16:42 UTC, xBromsson commented on .vscode/launch.json
Bro this opened my tiny eyes to debugger tool. Prior to reviewing this... debugging for me only consisted of 'click run, if error, fix error' lol. Now I know there is a whole arse tool for it in vscode that I can run line by line O.O

2023-08-17 16:42 UTC, xBromsson commented on .github/FUNDING.yml
Please remove moraroy and replace with label.

note: I saw that you corrected this in the #1 PR. My intention is to merge this PR and close the other one since this one contains most all of the other PRs additions. (I've never handled a PR before so please mentor me if there is a better way to handle PRs such as this where there are multiple PRs and some contain duplicate changes)

2023-08-17 17:03 UTC, pythoninthegrass commented on .gitignore
Correct. Boilerplate from the [gitignore extension](https://marketplace.visualstudio.com/items?itemName=codezombiech.gitignore). Personally add the `ETC` block for repo-specific exclusions.

2023-08-17 17:04 UTC, pythoninthegrass commented on .vscode/launch.json
It's a game changer for sure. Setting break points, inspecting objects, and copying expressions is super useful.

2023-08-17 17:06 UTC, pythoninthegrass commented on .github/FUNDING.yml
While that would technically work, understanding how to resolve merge conflicts is a good learning experience in and of itself. Technically so would removing extraneous files from commits, but there's a limit to my git patience / expertise — especially with personal repos lmao

Sidenote: my SRE mentor talked me into using [GitKraken](https://www.gitkraken.com/) and I now pay for an annual license bc it's _that_ good

2023-08-17 17:30 UTC, pythoninthegrass commented
Merged all PRs into #1 

![one ring et al](https://media.giphy.com/media/ZiK1I0ceU2FMc/giphy.gif)

2023-08-17 17:30 UTC, closed without merging